version: "3.4"
services:
    traefik:
        image: traefik:v2.1
        ports:
            - "80:80"
            - "8080:8080"
        volumes: 
            - "/var/run/docker.sock:/var/run/docker.sock"
        command: 
            - "--api.insecure=true"
            - "--api.dashboard=true"
            - "--accesslog=true"
            - "--providers.docker=true"
            - "--entrypoints.web.address=:80"
    whoami:
        image: containous/whoami
        labels: 
            - "traefik.http.routers.app.rule=Host(`localhost`)"
            - "traefik.http.routers.app.entrypoints=web"